### ISSUE TITLE
Fails to build with gcc 10

### ISSUE THREAD

**Issue by rfc1036** [besser82/libxcrypt#103]
The package fails to build in a test rebuild on at least amd64 with gcc-10/g++-10, but succeeds to build with gcc-9/g++-9.

The full build log can be found at: http://people.debian.org/~doko/logs/gcc10-20200225/libxcrypt_4.4.10-10_unstable_gcc10.log

To build with GCC 10, either set CC=gcc-10 CXX=g++-10 explicitly,
or install the gcc, g++, gfortran, ... packages from experimental.

  apt-get -t=experimental install g++

Common build failures are new warnings resulting in build failures with
-Werror turned on, or new/dropped symbols in Debian symbols files.
For other C/C++ related build failures see the porting guide at
http://gcc.gnu.org/gcc-10/porting_to.html

<pre>
/usr/bin/ld: lib/.libs/libcrypt_la-crypt-des-obsolete.o:./build-deb1/../lib/crypt-common.h:27: multiple definition of `_crypt_ascii64'; lib/.libs/libcrypt_la-alg-des-tables.o:./build-deb1/../lib/crypt-common.h:27: first defined here
</pre>

**Comment by rfc1036** [comment]
This is [Debian bug #957484](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=957484).

**Comment by besser82** [comment]
From the [NEWS](https://github.com/besser82/libxcrypt/blob/develop/NEWS) file:

```
Version 4.4.12
* Another fix for GCC v10.x, which occurs on s390 architectures only.

Version 4.4.11
* Fixes for GCC v10.x (issue #95).
* Change how the known-answer tests are parallelized.
```

If you really need to stick with v4.4.10, then you need to cherry-pick the following commits:

* https://github.com/besser82/libxcrypt/commit/45ff87405a6f2ee64ec282e6efc6cca229eae893
* https://github.com/besser82/libxcrypt/commit/941362e2868a71a32a2a497903e651fb647b4fd2
* https://github.com/besser82/libxcrypt/commit/0eb14f1e178a1ba9c897bb62db1f5ced3e6d9ab8

Anyways, I've seen v4.4.16 has already migrated to Debian testing, so this should not be an issue anymore?

**Comment by rfc1036** [comment]
Indeed, sorry for the noise: I did not notice that an old version was rebuilt.

**Comment by besser82** [comment]
No problem.  =)

This issue can be closed then?
