### ISSUE TITLE
Can't make/gmake on FreeBSD 12.1

### ISSUE THREAD

**Issue by SomeAB** [besser82/libxcrypt#110]
Platform: FreeBSD 12.1 64-bit (running inside Vmware Workstation Player 15) - 4 GB RAM
libxcrypt Release: 4.4.16

1. The Installation file says to use 'make' .. but when I try ./configure MAKE="make" it give me errors. 
a. bash ./autogen.sh output : http://bsd.to/cmc4
b. ./configure or ./configure MAKE="make" .. it gives me following error/output: https://bsd.to/nxDe

2. When I use gmake (4.3) instead using ./configure MAKE="gmake" 
b. running ./configure completes and give this output: https://bsd.to/sMXe
c. but breaks when I do gmake: http://bsd.to/SZzH

**Comment by zackw** [comment]
Hi, thanks for your interest in using libxcrypt on FreeBSD.  We would be happy to consider patches to improve binary compatibility with the system-provided libcrypt on this platform.

> ```
> config.status: error: in `/usr/home/user123/libxcrypt/libxcrypt-4.4.16':
> config.status: error: Something went wrong bootstrapping makefile fragments
>  for automatic dependency tracking. If GNU make was not used, consider
>  re-running the configure script with MAKE="gmake" (or whatever is
>  necessary). You can also try re-running configure with the
>  '--disable-dependency-tracking' option to at least be able to build
>  the package (albeit without support for automatic dependency tracking).
> See `config.log' for more details
> ```

I'm able to reproduce this on a FreeBSD 11 host, using autoconf 2.69 and automake 16.1.  This is a limitation in Automake; it does not support BSD make adequately.  There's not much I can do about it other than adding a note to the README about using either `--disable-dependency-tracking` or GNU make. You might consider reporting the problem to the Automake maintainers (see https://www.gnu.org/software/automake/manual/html_node/Reporting-Bugs.html ).

> ```
> In file included from lib/randombytes.c:35:
> /usr/include/unistd.h:489:8: error: redefinition of 'struct crypt_data'
>  489 | struct crypt_data {
>      |        ^~~~~~~~~~
> In file included from lib/crypt-port.h:397,
> from lib/randombytes.c:17:
> ./crypt.h:73:8: note: originally defined here
> 73 | struct crypt_data
>    |        ^~~~~~~~~~
> ```

This, on the other hand, I cannot reproduce on FreeBSD 11.  I don't have access to a FreeBSD 12 host, but I understand what's wrong anyway.  It's going to be a little awkward to fix and I don't have time to work on it today, but I may ask you to test a pull request sometime later this week.

**Comment by SomeAB** [comment]
Hello Zach. Thank you for taking note of it. 

Yeah, I'm using libxcrypt on FreeBSD because the crypt(3) on 12.1 doesn't have Salt Generation functions like the OpenBSD crypt(3). I wish I could find a way to safely generate salt somehow in my C code. I did manage to use arc4random_buf to generate random bytes. 

Ran the following tests just now on git-clone (4.4.17 version)
- yes I just checked that running " ./configure MAKE="make" --disable-dependency-tracking" successfully completes on my 12.1 host.  
- However, as soon as I try do make, I run into this error: https://bsd.to/ERtp
- Running just "./configure" also doesn't work. Running "./configure --disable-dependency-tracking" works

I also tried make++ aka makepp .. which is a drop-in replacement for GNU make .. 
- command "./configure MAKE="makepp" --disable-dependency-tracking" works fine (after ./autogen.sh obviously)
- but when I do "makepp" .. then I get the following error: https://bsd.to/38yB

Looking at the zh mention in first line of it (makepp error) makes me think should I explicitly do bash ./autogen.sh 
& bash 
(editing)

**Comment by besser82** [comment]
@SomeAB Can you please confirm #111 fixes the problem with `unistd.h` and `struct crypt_data` for you?

**Comment by SomeAB** [comment]
Hi Besser82 

I just tested it with the following:
`git clone --single-branch --branch topic/besser82/issue_110 https://github.com/besser82/libxcrypt.git
./autogen.sh
./configure MAKE="gmake" --disable-dependency-tracking
gmake
`

didn't work, got a new error: 
`/usr/local/bin/ld: .libs/libcrypt.so.2.0.0: version node not found for symbol crypt_checksalt@@XCRYPT_4.3
/usr/local/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status
gmake[1]: *** [Makefile:1449: libcrypt.la] Error 1
gmake[1]: Leaving directory '/usr/home/user123/libxcrypt/libxcrypt'
gmake: *** [Makefile:1272: all] Error 2`

**Comment by zackw** [comment]
That's a _different_ problem; we've gotten past the unistd.h type conflict successfully.  I need to see the complete `libtool` command line that should have appeared a few lines above the error message you quoted.  I also need to see the contents of the file `libcrypt.map` which should be at the top level of your build directory.

**Comment by SomeAB** [comment]
Here is my complete terminal output (319 lines only) from start to finish: https://pastebin.com/FCh2mF2k
Here are the contents of the libcrypt.map: 

> XCRYPT_2.0 {
>   global:
>     crypt_gensalt_ra;
>     crypt_gensalt_rn;
>     crypt_r;
>     crypt;
>     xcrypt_gensalt;
>     crypt_ra;
>     crypt_rn;
>     xcrypt;
>     crypt_gensalt_r;
>     crypt_gensalt;
>     xcrypt_r;
>     xcrypt_gensalt_r;
>   local:
>     *;
> };
> XCRYPT_4.3 {
>   global:
>     crypt_checksalt;
> } XCRYPT_2.0;
> XCRYPT_4.4 {
>   global:
>     crypt_preferred_method;
> } XCRYPT_2.0;

**Comment by SomeAB** [comment]
any update on this @zackw ?

**Comment by besser82** [comment]
@SomeAB With the two commits added in #111, I can compile successfully from a fully clean (`git clean -dfx`) sourcedir on FreeBSD 12.1 x64_86.  The testsuite fully passes and all seems to be fine.

Can you please retry and confirm?

**Comment by SomeAB** [comment]
nope. I'm still getting the exact same error as above on gmake. I also did `rm -R libxcrypt` to remove all file in that folder, before trying again (besides trying 'git clean -dfx' and then starting from ./autogen.sh'

**Comment by SomeAB** [comment]
I hope @zackw is okay as well, and gets time to see into this soon. 

I too got infected with COVID19 around the time I last commented. Thank Almighty, I'm nearly recovered now, just waiting for quarantine period to end. 

thanks for the good work guys.

**Comment by besser82** [comment]
@SomeAB If you still have issues building, please open a new issue, as the initial problem here has been solved.
