### ISSUE TITLE
configure.ac:58: error: possibly undefined macro: LT_SYS_SYMBOL_USCORE

### ISSUE THREAD

**Issue by rhclayto** [besser82/libxcrypt#125]
When running autogen.sh, I get:

```
autoreconf: running: /usr/bin/autoconf --warnings=all,error
configure.ac:58: error: possibly undefined macro: LT_SYS_SYMBOL_USCORE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

Ubuntu 20.04, with the following packages installed:

 cmake autoconf-archive build-essential libtool automake autoconf pkg-config

Commenting out the following allowed it to complete (no idea if this will break anything):

```
# The test scripts need to know whether C global symbols have a
# leading underscore.
#LT_SYS_SYMBOL_USCORE
#if test x$sys_symbol_underscore = xno; then
#  SYMBOL_PREFIX=
#else
#  SYMBOL_PREFIX=_
#fi
#AC_SUBST([SYMBOL_PREFIX])
```

**Comment by rfc1036** [comment]
`apt install libltdl-dev`

Also, if you want to work on libxcrypt on Debian/Ubuntu you should really start from the Debian package.

**Comment by rhclayto** [comment]
Thank you, that worked. I also didn't know about the package, thanks for the heads up.

**Comment by dg0yt** [comment]
Do I understand correctly that this used only for tests (via SYMBOL_PREFIX)?
