### ISSUE TITLE
Release tarballs generated with `make dist`

### ISSUE THREAD

**Issue by mattst88** [besser82/libxcrypt#134]
Hello,

We're in the process of transitioning to libxcrypt in Gentoo. We noticed that there's an annoying circular dependency that would be avoided if libxcrypt's tarballs were generated with `make dist` and thus included a generated `configure` script.

The dependency loop is: libxcrypt depends on automake to process libxcrypt's `Makefile.am`s, and automake requires perl, which requires libcrypt.so, which requires perl.

Could you generate "release" tarballs and attach them to the Releases page? For example, the ZFS project does this: https://github.com/openzfs/zfs/releases/tag/zfs-2.0.5

I suspect libxcrypt's build-time dependence on perl could also be avoided in `make dist`-generated tarballs easily if it's not already wired up. I'm happy to help do that.

I think it's possible to automatically create and upload the `make dist`-generated tarball with GitHub actions as well, though I can't offer advice on how to do that.

**Comment by zackw** [comment]
Thanks for the suggestion!  Right now we have no CI and therefore no clean environment to generate tarballs in, but once we finish transitioning to Github Actions, this should be possible.  See #131 to track progress on the transition.

> I suspect libxcrypt's build-time dependence on perl could also be avoided in make dist-generated tarballs easily 

I regret to say this will _not_ be possible.  perl is used during the build proper, to generate code dependent on configure options, and there's probably going to be more of that in the future.

**Comment by mattst88** [comment]
Thanks!

> I regret to say this will not be possible. perl is used during the build proper, to generate code dependent on configure options, and there's probably going to be more of that in the future.

Acknowledged. We realized that shortly after posting this issue.

**Comment by besser82** [comment]
First signed release: https://github.com/besser82/libxcrypt/releases/tag/v4.4.26
