### ISSUE TITLE
support SM3 hash algorithm

### ISSUE THREAD

**Issue by myhou0418** [besser82/libxcrypt#149]
Do we have plans to support the SM3 algorithm? Libgcrypt already supports SM3.

**Comment by solardiz** [comment]
I hope not! SM3 is a fast hash, not a password hash, and it would be a vulnerability to directly use it for passwords.

**Comment by myhou0418** [comment]
Is SHA256 a vulnerability to directly use for passwords?
The SM3 algorithm is an improved algorithm based on SHA-256. The compression function of the SM3 algorithm has a similar structure to the compression function of SHA-256, but the design of the SM3 algorithm is more complicated. For example, each round of the compression function uses 2 message words.

**Comment by solardiz** [comment]
> Is SHA256 a vulnerability to directly use for passwords?

Yes, of course!
