### ISSUE TITLE
Build error with gcc 12.1

### ISSUE THREAD

**Issue by sonic42** [besser82/libxcrypt#155]
First build tests (4.4.28) with gcc 12.1 produce this failure message:

/bin/bash ./libtool  --tag=CC   --mode=compile x86_64-cross-linux-gnu-gcc -DHAVE_CONFIG_H -I.  -I./lib -DIN_LIBCRYPT  -Wall -Wextra -Walloc-zero -Walloca -Wbad-function-cast -Wcast-align -Wcast-qual -Wconversion -Wformat=2 -Wformat-overflow=2 -Wformat-signedness -Wformat-truncation=1 -Wlogical-op -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wnull-dereference -Wold-style-definition -Wpointer-arith -Wrestrict -Wshadow -Wstrict-overflow=2 -Wstrict-prototypes -Wundef -Wvla -Wwrite-strings -Wpedantic -Werror -fno-plt -O2 -pipe -Wall -fexceptions -fPIC -m64 -mtune=native   -MT lib/libcrypt_la-crypt-gost-yescrypt.lo -MD -MP -MF lib/.deps/libcrypt_la-crypt-gost-yescrypt.Tpo -c -o lib/libcrypt_la-crypt-gost-yescrypt.lo `test -f 'lib/crypt-gost-yescrypt.c' || echo './'`lib/crypt-gost-yescrypt.c
In function 'des_gen_hash',
    inlined from '_crypt_crypt_descrypt_rn' at lib/crypt-des.c:202:3:
lib/crypt-des.c:127:10: error: assuming pointer wraparound does not occur when comparing P +- C1 with P +- C2 [-Werror=strict-overflow]
  127 |       if (sptr >= end)
      |          ^
lib/crypt-des.c:127:10: error: assuming pointer wraparound does not occur when comparing P +- C1 with P +- C2 [-Werror=strict-overflow]
cc1: all warnings being treated as errors
make[2]: *** [Makefile:2019: lib/libcrypt_la-crypt-des.lo] Error 1
make[2]: *** Waiting for unfinished jobs....

**Comment by besser82** [comment]
@sonic42 does this problem still occur?

**Comment by sonic42** [comment]
Can be closed... With gcc 12.2 have no problems.

**Comment by besser82** [comment]
Allright!  Thank you!

**Comment by besser82** [comment]
Re-opening, as this is related to #163.

**Comment by besser82** [comment]
Fixed in release [v4.4.31](https://github.com/besser82/libxcrypt/releases/tag/v4.4.31).
