### ISSUE TITLE
RFC3779 isn’t supported

### ISSUE THREAD

**Issue by alarig** [besser82/libxcrypt#156]
Hello,

I tried to install a package that needs RFC3779 support in libcrypto and it fails:
```
configure: error: libcrypto with RFC3779 support required

!!! Please attach the following file when seeking support:
!!! /var/tmp/portage/net-misc/rpki-client-7.9/work/rpki-client-7.9/config.log
 * ERROR: net-misc/rpki-client-7.9::SwordArMor failed (configure phase):
 *   econf failed
```

I don’t know what you need to test it and improve this issue, so please tell me!

**Comment by thesamesam** [comment]
libcrypto is from OpenSSL, while libcrypt is something different (this project). I bet you want to enable USE=rfc3779 on dev-libs/openssl.

**Comment by alarig** [comment]
It’s indeed what I want. Sorry for the confusion!
