### ISSUE TITLE
No tag 4.4.37

### ISSUE THREAD

**Issue by yurivict** [besser82/libxcrypt#177]
Commit messages say that 4.4.37 was released but there is no such tag.

**Comment by thesamesam** [comment]
Are you sure? https://github.com/besser82/libxcrypt/commit/72f75aa370ae96ccd2cc44ea3cf4182d8679ffbe seems to just follow the pattern of previous releases (incrementing version _post_ tag).

**Comment by yurivict** [comment]
I am looking [here](https://github.com/besser82/libxcrypt/tags).

**Comment by thesamesam** [comment]
Yes, I'm saying that the commit you're referring to is normal for libxcrypt's development, and hence the absence of a tag is fine, because they always do the "increment version" commit to n+1 after tagging n.

**Comment by zackw** [comment]
Yes, this is normal.  4.4.37 has not yet been released; the tag will be created when the release happens.
