### ISSUE TITLE
configure - autoreconf -vif

### ISSUE THREAD

**Issue by gzpapp** [besser82/libxcrypt#23]
I'm trying to run autoreconf -vif in the top directory, but getting the following error:

Makefile.am:29: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:29:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:29:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:29:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:29:   its definition is in aclocal's search path.
Makefile.am:38: error: 'pkgconfig_DATA' is used but 'pkgconfigdir' is undefined

**Comment by zackw** [comment]
`LT_INIT` does appear in configure.ac, and `pkgconfigdir` is supposed to be defined by `PKG_INSTALLDIR`.  Also, I frequently use `autoreconf -vif` myself and it works fine.  There must be something else wrong. Could you please post the _complete and unedited_ output of `autoconf --version`, `autoreconf --version`, `automake --version`, `aclocal --version`, `libtoolize --version`, and `autoreconf -vif` in a clean git checkout?  This is what I get when I run those commands:

```
$ autoconf --version
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
$ autoreconf --version
autoreconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
$ automake --version
automake (GNU automake) 1.15.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.
$ aclocal --version
aclocal (GNU automake) 1.15.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.
$ libtoolize --version
libtoolize (GNU libtool) 2.4.6
Written by Gary V. Vaughan <gary@gnu.org>, 2003

Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ autoreconf -vif
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'm4'.
libtoolize: copying file 'm4/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:26: installing 'm4/compile'
configure.ac:25: installing 'm4/config.guess'
configure.ac:25: installing 'm4/config.sub'
configure.ac:16: installing 'm4/install-sh'
configure.ac:16: installing 'm4/missing'
Makefile.am: installing './INSTALL'
Makefile.am: installing 'm4/depcomp'
parallel-tests: installing 'm4/test-driver'
autoreconf: Leaving directory `.'
```

It would also be helpful to know what operating system you are trying to build for, in detail (e.g. if Linux then tell us which distribution and its approximate age).

**Comment by gzpapp** [comment]
On 07/27/18 14:35, Zack Weinberg wrote:

> |LT_INIT| does appear in configure.ac, and |pkgconfigdir| is supposed to be
> defined by |PKG_INSTALLDIR|. Also, I frequently use |autoreconf -vif| myself
> and it works fine. There must be something else wrong.

After investigating the log files I discovered, that an installed libtool was 
missing.
Now seems autoreconf -vif works fine without any error.

Sorry for the noise.

**Comment by gzpapp** [comment]
Found in the configure log:

configure: line 4372: PKG_PROG_PKG_CONFIG: command not found
configure: line 4373: PKG_INSTALLDIR: command not found

From the configure script the above lines looks like:

# Dependencies
PKG_PROG_PKG_CONFIG
PKG_INSTALLDIR

**Comment by gzpapp** [comment]
My fault again, related to this error:

Makefile.am:38: error: 'pkgconfig_DATA' is used but 'pkgconfigdir' is undefined.

From the beginning:

$ autoconf --version
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.

$ autoreconf --version
autoreconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.

$ automake --version
automake (GNU automake) 1.15
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.

$ aclocal --version
aclocal (GNU automake) 1.15
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.

$ libtoolize --version
libtoolize (GNU libtool) 2.4.6
Written by Gary V. Vaughan <gary@gnu.org>, 2003

Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ autoreconf -vif
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'm4'.
libtoolize: copying file 'm4/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:26: installing 'm4/compile'
configure.ac:25: installing 'm4/config.guess'
configure.ac:25: installing 'm4/config.sub'
configure.ac:16: installing 'm4/install-sh'
configure.ac:16: installing 'm4/missing'
Makefile.am: installing './INSTALL'
Makefile.am: installing 'm4/depcomp'
Makefile.am:38: error: 'pkgconfig_DATA' is used but 'pkgconfigdir' is undefined
parallel-tests: installing 'm4/test-driver'
autoreconf: automake failed with exit status: 1

**Comment by gzpapp** [comment]
Installing missing pkgconf solved the problem:

$ pkgconf --version
0.28

I was missing libtool and pkgconf. Now autoreconf -vif works fine.

**Comment by ldv-alt** [comment]
btw, pkgconf is not the only option available, one can use e.g. pkg-config >= 0.27 instead.

**Comment by gzpapp** [comment]
On debian stable pkg-config is symlink to pkgconf.

**Comment by ldv-alt** [comment]
pkg-config is symlink to pkgconf only if pkgconf package is installed.

**Comment by gzpapp** [comment]
distro madness :-P
Anyway, one of them needed for running autoreconf -vif

**Comment by zackw** [comment]
Requirements for building from a git checkout are now documented in README.md.  Please let us know if there's still something missing.

**Comment by gzpapp** [comment]
Looks good, thanks for your work!
