### ISSUE TITLE
error: 'IS_BIGENDIAN' is not defined, evaluates to 0

### ISSUE THREAD

**Issue by ryandesign** [besser82/libxcrypt#42]
After fixing the other issues I reported, libxcrypt fails to build with this error—if I build universal:

```
alg-sha1.c:84:5: error: 'IS_BIGENDIAN' is not defined, evaluates to 0 [-Werror,-Wundef]
#if IS_BIGENDIAN
    ^
1 error generated.
make[1]: *** [libcrypt_la-alg-sha1.lo] Error 1
```

The configure script is trying to `#define IS_BIGENDIAN 1` on big-endian systems and `#define IS_BIGENDIAN 0` on little-endian systems, but autoconf has a third value for its endian check when building universal:

```
checking whether byte ordering is bigendian... universal
```

A [universal binary](https://en.wikipedia.org/wiki/Universal_binary) is a macOS feature that allows a developer to distribute a single binary that runs on any Mac regardless of what processor it uses. Building universal is ideally accomplished by running `./configure` a single time, supplying multiple `-arch` flags in `CFLAGS`, `CXXFLAGS`, `LDFLAGS` etc., then running `make` and `make install` a single time. When invoked with multiple `-arch` flags, the compiler internally runs itself once per architecture and then glues the results into a single file using `lipo`.

This method requires you not to attempt to detect endianness or bitness at configure time. Autoconf's universal "support" was designed when "universal" meant building for 32-bit PowerPC and 32-bit Intel (e.g. `-arch i386 -arch ppc`)—the bitness was the same but the endianness differed. When autoconf detects that multiple `-arch` flags are used, it therefore answers that the endianness is "universal" to ensure you don't rely on this result. On modern systems, "universal" means building for 32-bit Intel and 64-bit Intel (e.g. `-arch i386 -arch x86_64`)—the endianness is the same but the bitness differs—but autoconf has not been updated to detect that the endianness is the same, so it still answers "universal".

A less-ideal way of building universal is to create two build directories, and in one, `./configure`, `make` and `make install` with one arch, do the same with the other arch in the other directory, and then manually `lipo` any binary files together, and I can do that if necessary, but it would be great if it weren't.

I recommend removing the `IS_BIGENDIAN` stuff entirely and instead use `#ifdef __BIG_ENDIAN__`; compilers on macOS have that predefined for you. And if you want to know if you're on 64-bit vs 32-bit, you can check `#ifdef __LP64__`. I don't know how well supported these defines are on compilers used on non-Mac platforms.

**Comment by besser82** [comment]
Please check the patch proposed in #44.
