### ISSUE TITLE
Fedora package maintenance

### ISSUE THREAD

**Issue by fweimer** [besser82/libxcrypt#58]
@besser82, it seems you are not reading your Fedora email, so I'm trying to contact you in this manner.

Fedora's non-responsive package maintainer process was activated while you were away, and the libxcrypt package was transferred to me. Since you seem to be doing package updates again, I would suggest you take ownership again.

I can stay around as a co-maintainer, but I do not plan to make any changes.

Thanks

**Comment by besser82** [comment]
Just responded by PM.
