### ISSUE TITLE
Missing symbols

### ISSUE THREAD

**Issue by tpgxyz** [besser82/libxcrypt#77]
Hi,

libxcrypt when it is compiled with LLVM/clang and linked with ld.gold does not export all needed symbols.
After further investigation, changing linker to ld.bfd gives right output.

More details here:
https://github.com/OpenMandrivaAssociation/libxcrypt/commit/2f0240ebf066a0b0cb626e18b4a096c13e8773c5

**Comment by besser82** [comment]
As I cannot reproduce this issue with LLVM/Clang v6+, can you please give me a bit more information?  Which version of LLVM/Clang is used during compilation?  Which {C,LD}FLAGS are exactly used?

***

Anyways, you should run `%make_build check` during the `%check` stage of the spec file to make sure everything is working…

**Comment by tpgxyz** [comment]
@besser82 Please see full logs here (where you will find all the answers for your questions)
https://abf.openmandriva.org/build_lists/358431

Spec file for libxcrypt:
https://github.com/OpenMandrivaAssociation/libxcrypt/blob/master/libxcrypt.spec

We are using LLVM/clang-7.0.1

CFLAGS='-Os -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4  -fPIC -flto -O3 -falign-functions=32 -fno-math-errno -fno-trapping-math -fno-strict-aliasing -fuse-ld=bfd'
+ LDFLAGS='-Os -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4  -fPIC -flto -O3 -falign-functions=32 -fno-math-errno -fno-trapping-math -fno-strict-aliasing -fuse-ld=bfd -O3 -fuse-ld=bfd

**Comment by besser82** [comment]
I've done some testing with

```
clang version 7.0.1 (Fedora 7.0.1-1.fc29)
GNU gold (version 2.31.1-15.fc29) 1.16
```

and I cannot reproduce this problem on Fedora 29+ with the specified versions of `clang` and `ld.gold`.

Looking at OpenMandriva's versions of the toolchain it seems OM uses much more modifications compared to the Fedora builds.  Thus I assume the problem arises from the toolchain used.

Does this happen with other libraries using version-scripts + lto in OM, too?

**Comment by tpgxyz** [comment]
Well yes, in case of toolchain we are preety much more adavanced than others.

We noticed missing symbols only in libxcrypt, that's why we added extra check in spec file.
If crypt_r@GLIBC_2 symbol is missing then build is terminated

https://github.com/OpenMandrivaAssociation/libxcrypt/blob/e75d51a18c0d7dd94be4bd2dc5f936ead89b0c82/libxcrypt.spec#L88

Btw. currently libxcrypt cannot be build on armv7hnl arch because ld.bfd segfaults on that arch, and building with lg.gold produces missing symbols.

@berolinux Can you please help here ?

**Comment by besser82** [comment]
Ping, @tpgxyz and @berolinux.

Is this still an issue?

**Comment by tpgxyz** [comment]
@besser82  Yes issue still exists:
http://file-store.openmandriva.org/api/v1/file_stores/ad3765a117bf1d3bd38866cffae14aaaf66e9a67.log?show=true

```
FAIL: test-symbols-static
=========================
*** Extra symbols: C D T 
*** Missing symbols: crypt crypt_checksalt crypt_gensalt crypt_gensalt_r crypt_gensalt_ra crypt_gensalt_rn crypt_preferred_method crypt_r crypt_ra crypt_rn xcrypt xcrypt_gensalt xcrypt_gensalt_r xcrypt_r 
FAIL test-symbols-static.sh (exit status: 1)
FAIL: test-symbols-renames
==========================
```

**Comment by tpgxyz** [comment]
@berolinux found the issue. It was caused by LTO which is enabled in OpenMandriva by default.
