### ISSUE TITLE
NTHASH truncates passwords to 128 chars, which may be wrong

### ISSUE THREAD

**Issue by zackw** [besser82/libxcrypt#78]
Our implementation of NTHASH truncates passwords to 128 characters.  This appears to be inconsistent with [Microsoft's documentation](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/hh994558(v=ws.10)), which says

> The NT hash is simply a hash. The password is hashed by using the MD4 algorithm and stored... Internally, Windows represents passwords in 256-character UNICODE strings. The logon dialog box is limited to 127 characters. Therefore, the longest password that can be used to log on interactively to a computer running Windows is 127 characters. Programs such as services can use longer passwords, but they must be set programmatically.

Going by that, we ought to truncate at either 127 or 256 characters, not 128.  I want to check what the BSD clone did before making any changes, though.

**Comment by besser82** [comment]
Our implementation is exactly the one (with slight modifications) from FreeBSD, which is the only BSD supporting it.

**Comment by mbretter** [comment]
Sorry, I have no idea, why I made it this way, maybe it was easier because of the division by 2, when computing the unicode? Sorry I can't remember, 15 years it's a long time ...

**Comment by besser82** [comment]
@mbretter Thank you for your reply.

@zackw Given that simple reasoning (it actually came into mind before as well), are you okay with simply truncating `phrase` to a maximum length of 127 bytes then?  I already have an improved version of NTHASH with this change ready to go.

**Comment by mbretter** [comment]
It think that I took the code from Mpd (I did some work on it at those days):
https://sourceforge.net/p/mpd/svn/HEAD/tree/trunk/src/msoft.c
=> NTPasswordHash

therefore the comment in the code mentioning Archie

**Comment by besser82** [comment]
> It think that I took the code from Mpd (I did some work on it at those days):
> https://sourceforge.net/p/mpd/svn/HEAD/tree/trunk/src/msoft.c
> => NTPasswordHash
> 
> therefore the comment in the code mentioning Archie

Let's ask @archiecobbs about it then…

**Comment by archiecobbs** [comment]
As I recall, the 128 hard limit is just an upper bound and, at the time (> 25 years ago), was used simply because it was (a) "long enough", and (b) easier to code.

The correct fix here would be to dynamically allocate a buffer of suitable size using `malloc()`, instead of using a fixed-width buffer which causes truncation.

**Comment by besser82** [comment]
@zackw Looking at the explaination by @archiecobbs (thanks for that), we possibly should drop the truncation at all, and use a unicode buffer that is `CRYPT_MAX_PASSPHRASE_SIZE` units long.

What do you think?

**Comment by zackw** [comment]
That seems plausible to me.

The only actual use case for `$3$` hashes anymore is something like an LDAP server for Windows clients. (Windows 10 still uses this hashing method!) The Windows documentation says that passphrases up to 256 "characters" (in context, these are probably UCS-2 code units) can be set programmatically (e.g. via [`NetUserChangePassword`](https://docs.microsoft.com/en-us/windows/desktop/api/lmaccess/nf-lmaccess-netuserchangepassword)), but the user interface limits input to 127 characters.  I get the impression that Windows does not _truncate_ passphrases; rather, the API would error out on overlong input, and the UI would refuse to record more characters.

`CRYPT_MAX_PASSPHRASE_SIZE` is 512 bytes. So, if we drop the truncation, we can generate a correct `$3$` hash for any passphrase that could have been input on the Windows side, as long as its use of Unicode is limited to the U+0000..U+00FF range.  We can also generate hashes that don't correspond to any Windows passphrase, e.g. `$3$$9ea4b5b39c3e6fdfabac4706aa2e2b39` is the hash of 512 'x' characters in a row, but this just means the hypothetical LDAP server has an account that no one can log into.  (Well, I suppose there might be an MD4 collision that's short enough to be input.)

I pushed a patch on top of your `besser82/fix_nthash` branch that implements this, please feel free to make further changes.
