### ISSUE TITLE
Patches porting libcrypto, libgcrypt (any other?) to libxcrypt

### ISSUE THREAD

**Issue by kloczek** [besser82/libxcrypt#83]
Someone maybe have some list of projects libxcrypt ready and/or list of patches which can be applied on some projects porting them from any existing crypto API to libxcrypt?

Just made few dnf queries to asses which one projects on Fedora are using existing crypto ABIs:
Please leave here some comment if you know that some of below projects can be already switched to use libxcrypt.

<pre># (dnf repoquery -q --whatrequires &apos;libgcrypt.so.20()(64bit)&apos; --qf &quot;libgcrypt %{source_name}&quot;; dnf repoquery -q --whatrequires &apos;libcrypto.so.1.1()(64bit)&apos; --qf &quot;libcrypto %{source_name}&quot;)|sort -k2|uniq
libcrypto 0install
libgcrypt abiword
libcrypto activemq-cpp
libcrypto afflib
libgcrypt afpfs-ng
libgcrypt aide
libcrypto aircrack-ng
libcrypto alpine
libcrypto amanda
libgcrypt amarok
libcrypto android-tools
libcrypto apr-util
libcrypto apt-cacher-ng
libcrypto arc-gui-clients
libcrypto asterisk
libcrypto authd
libcrypto axel
libcrypto bacula
libcrypto balsa
libcrypto bannergrab
libcrypto bigloo
libcrypto bind
libcrypto bip
libcrypto BitchX
libgcrypt bitlbee
libgcrypt bitlbee-steam
libcrypto boinc-client
libgcrypt booth
libcrypto borgbackup
libcrypto botan2
libcrypto burp
libcrypto calibre
libcrypto canl-c
libcrypto cardpeek
libcrypto casync
libcrypto ccnet
libgcrypt ccrtp
libcrypto ceph
libcrypto certmonger
libcrypto CGSI-gSOAP
libcrypto cherokee
libgcrypt chntpw
libcrypto cjose
libcrypto clamav
libgcrypt clamz
libcrypto classified-ads
libcrypto clevis
libcrypto collectd
libgcrypt collectd
libcrypto community-mysql
libcrypto condor
libcrypto cone
libcrypto conserver
libcrypto coreutils
libcrypto cowpatty
libcrypto cpprest
libgcrypt crda
libcrypto createrepo_c
libcrypto cryptsetup
libcrypto ctk
libcrypto ctorrent
libcrypto curl
libgcrypt cyphesis
libcrypto cyrus-imapd
libcrypto cyrus-sasl
libgcrypt dar
libcrypto datovka
libcrypto davix
libcrypto dcap
libcrypto dcmtk
libcrypto deletemail
libcrypto dillo
libgcrypt dino
libcrypto dionaea
libcrypto dmlite
libcrypto dnsdist
libcrypto dnssec-check
libcrypto dnssec-nodes
libcrypto dnssec-tools
libcrypto dnssec-trigger
libcrypto dolphin-connector
libcrypto domoticz
libcrypto dovecot
libcrypto dpm-xrootd
libcrypto dpsearch
libcrypto drpm
libcrypto dsniff
libcrypto echoping
libcrypto ecryptfs-utils
libcrypto efl
libcrypto eiskaltdcpp
libcrypto elinks
libcrypto EMBOSS
libcrypto epic
libcrypto erlang
libcrypto erlang-fast_tls
libcrypto exim
libcrypto facter
libcrypto falkon
libgcrypt fapolicyd
libcrypto fastd
libcrypto fawkes
libcrypto fetchmail
libcrypto fipscheck
libcrypto fossil
libcrypto freeipa
libgcrypt freeipmi
libcrypto freeradius
libcrypto freerdp
libgcrypt frogr
libgcrypt fsarchiver
libgcrypt fuse-emulator-utils
libcrypto fuse-encfs
libcrypto galera
libcrypto gambas3
libgcrypt GarminPlugin
libgcrypt gcr
libcrypto gdal
libcrypto gdcm
libcrypto gearmand
libcrypto getdns
libgcrypt ggz-base-libs
libcrypto ghasher
libcrypto git
libcrypto git-crypt
libcrypto gkrellm
libcrypto glite-jobid-api-c
libcrypto glite-lb-server
libcrypto globus-ftp-client
libcrypto globus-gass-cache
libcrypto globus-gass-copy
libcrypto globus-gatekeeper
libcrypto globus-gram-job-manager
libcrypto globus-gridftp-server
libcrypto globus-gridmap-eppn-callout
libcrypto globus-gridmap-verify-myproxy-callout
libcrypto globus-gsi-callback
libcrypto globus-gsi-cert-utils
libcrypto globus-gsi-credential
libcrypto globus-gsi-openssl-error
libcrypto globus-gsi-proxy-core
libcrypto globus-gsi-proxy-ssl
libcrypto globus-gsi-sysconfig
libcrypto globus-gssapi-gsi
libcrypto globus-openssl-module
libcrypto globus-proxy-utils
libcrypto glusterfs
libcrypto gnokii
libgcrypt gnome-keyring
libgcrypt gnomint
libgcrypt gnupg2
libgcrypt gnupg-pkcs11-scd
libcrypto godot
libgcrypt gq
libcrypto gridsite
libcrypto grisbi
libgcrypt grive2
libcrypto groonga
libcrypto grpc
libcrypto grub-customizer
libcrypto gsi-openssh
libcrypto gsoap
libcrypto gssntlmssp
libcrypto gstreamer1-plugins-bad-free
libgcrypt gtkhash
libgcrypt gtk-vnc
libcrypto guacamole-server
libgcrypt gvfs
libcrypto gwenhywfar
libgcrypt gwenhywfar
libcrypto haproxy
libcrypto hexchat
libcrypto hfsplus-tools
libcrypto hitch
libcrypto hostapd
libcrypto hplip
libcrypto htdig
libcrypto httpd
libcrypto httping
libcrypto http_ping
libcrypto httrack
libcrypto hydra
libgcrypt idzebra
libcrypto ike-scan
libcrypto ima-evm-utils
libcrypto imapfilter
libcrypto inn
libcrypto ipmitool
libcrypto ipmiutil
libcrypto iputils
libcrypto ipv6calc
libcrypto ircd-ratbox
libgcrypt irc-otr
libcrypto irssi
libcrypto iscsi-initiator-utils
libcrypto isns-utils
libcrypto isync
libcrypto jabberd
libgcrypt jd
libcrypto jose
libgcrypt jpilot
libcrypto kea
libcrypto keepalived
libgcrypt keepassx
libgcrypt keepassxc
libgcrypt kf5-kwallet
libgcrypt kf5-libktorrent
libcrypto kicad
libcrypto krb5
libcrypto kronosnet
libgcrypt ktp-common-internals
libcrypto kvirc
libcrypto lasso
libcrypto lastpass-cli
libcrypto lcgdm
libcrypto lcmaps
libcrypto ldapvi
libcrypto ldns
libcrypto libarchive
libcrypto libcoap
libcrypto libcouchbase
libcrypto libdap
libcrypto libdigidocpp
libcrypto libdnf
libcrypto libesmtp
libcrypto libevent
libcrypto libewf
libcrypto libeXosip2
libgcrypt libgcrypt
libcrypto libgda
libgcrypt libgda
libcrypto libgit2
libgcrypt libgnome-keyring
libgcrypt libimobiledevice
libcrypto libircclient
libgcrypt libiscsi
libgcrypt libisds
libgcrypt libktorrent
libcrypto liblrdf
libgcrypt libmtp
libcrypto libndn-cxx
libcrypto libopensync-plugin-opie
libcrypto libopkele
libgcrypt libotr
libcrypto libpq
libcrypto libquentier
libgcrypt libquvi
libcrypto librabbitmq
libcrypto librdkafka
libcrypto librepo
libcrypto libs3
libgcrypt libsecret
libcrypto libserf
libgcrypt libspectrum
libcrypto libssh
libcrypto libssh2
libcrypto libstoragemgmt
libcrypto libtorrent
libcrypto libtpms
libgcrypt libvncserver
libcrypto libwebsockets
libgcrypt libxslt
libcrypto libzdb
libcrypto libzip
libcrypto libzypp
libgcrypt lifeograph
libgcrypt lightdm
libcrypto lighttpd
libcrypto links
libcrypto linphone
libcrypto loudmouth
libcrypto lterm
libcrypto lua-cqueues
libcrypto lua-sec
libcrypto lua-sql
libgcrypt lxqt-wallet
libcrypto lynx
libcrypto m2crypto
libcrypto mail-notification
libcrypto mailx
libcrypto makepasswd
libcrypto mariadb
libcrypto mariadb-connector-c
libcrypto megatools
libcrypto mktorrent
libcrypto mmapper
libcrypto mod_auth_gssapi
libcrypto mod_auth_mellon
libcrypto mod_auth_openid
libcrypto mod_auth_openidc
libcrypto mod_http2
libcrypto mod_qos
libcrypto mokutil
libcrypto mongo-c-driver
libcrypto mongodb
libcrypto mongoose
libcrypto mongo-tools
libcrypto monit
libgcrypt monkeysphere
libcrypto mosh
libcrypto mosquitto
libcrypto mstflint
libcrypto mtxclient
libcrypto mumble
libgcrypt munge
libcrypto mupdf
libcrypto myproxy
libcrypto n2n
libcrypto nagios-plugins
libcrypto neon
libgcrypt netcf
libcrypto net-snmp
libcrypto nextcloud-client
libcrypto nghttp2
libcrypto nginx
libcrypto nheko
libcrypto nmap
libcrypto nmh
libcrypto nodejs
libcrypto nordugrid-arc
libcrypto nrpe
libcrypto nsd
libgcrypt ntfs-3g
libcrypto ntp
libcrypto ocaml-mysql
libcrypto ocaml-ssl
libcrypto ocspd
libcrypto omniORB
libcrypto opal
libcrypto openarc
libgcrypt openconnect
libcrypto opencryptoki
libcrypto opendkim
libcrypto opendnssec
libcrypto openfortivpn
libcrypto openhpi
libgcrypt openhpi
libcrypto OpenIPMI
libcrypto openldap
libcrypto opensc
libgcrypt openscap
libcrypto openslp
libcrypto openssh
libcrypto openssl
libcrypto openssl-gost-engine
libcrypto openssl-ibmpkcs11
libcrypto openssl-pkcs11
libgcrypt openvas-gsa
libgcrypt openvas-libraries
libgcrypt openvas-scanner
libcrypto open-vm-tools
libcrypto openvpn
libcrypto openvswitch
libcrypto openwsman
libcrypto ophcrack
libcrypto opusfile
libcrypto orangefs
libcrypto orthanc
libcrypto ortp
libcrypto ostree
libcrypto p11-remote
libcrypto pacman
libcrypto paho-c
libgcrypt pam_ccreds
libgcrypt pam-kwallet
libcrypto pam_mount
libcrypto pam_mysql
libgcrypt pdfgrep
libcrypto pdns
libcrypto pdns-recursor
libcrypto pen
libgcrypt percona-xtrabackup
libcrypto perdition
libgcrypt perl-Crypt-GCrypt
libcrypto perl-Crypt-OpenSSL-AES
libcrypto perl-Crypt-OpenSSL-Bignum
libcrypto perl-Crypt-OpenSSL-DSA
libcrypto perl-Crypt-OpenSSL-EC
libcrypto perl-Crypt-OpenSSL-ECDSA
libcrypto perl-Crypt-OpenSSL-PKCS10
libcrypto perl-Crypt-OpenSSL-Random
libcrypto perl-Crypt-OpenSSL-RSA
libcrypto perl-Crypt-OpenSSL-X509
libcrypto perl-Crypt-SMIME
libcrypto perl-Crypt-SSLeay
libcrypto perl-Net-DNS-SEC
libcrypto perl-Net-SSLeay
libcrypto pgbouncer
libcrypto php
libcrypto php-pecl-event
libcrypto php-pecl-http
libgcrypt pidgin-otr
libcrypto pidgin-sipe
libcrypto pixiewps
libcrypto pjproject
libcrypto pkcs11-dump
libcrypto pkcs11-helper
libcrypto pl
libgcrypt planner
libcrypto poco
libcrypto podofo
libcrypto poedit
libgcrypt pokerth
libcrypto postfix
libcrypto postgresql
libcrypto postgresql-pgpool-II
libcrypto ppp
libcrypto proftpd
libcrypto prosody
libcrypto proxysql
libcrypto proxytunnel
libgcrypt psi
libgcrypt psi-plus
libcrypto pulseaudio
libcrypto pure-ftpd
libgcrypt purple-matrix
libgcrypt purple-telegram
libgcrypt pwmd
libcrypto pwsafe
libcrypto pypy
libcrypto pyrit
libcrypto python3
libcrypto python36
libcrypto python38
libcrypto python-cryptography
libcrypto python-m2ext
libcrypto python-pycurl
libcrypto python-scrypt
libcrypto qca
libgcrypt qca
libcrypto qdigidoc
libcrypto qmasterpassword
libcrypto qpid-proton
libcrypto qt
libcrypto qt5-qtbase
libcrypto qterm
libcrypto quagga
libcrypto quassel-irssi
libcrypto rb_libtorrent
libcrypto rdesktop
libcrypto RdRand
libgcrypt recutils
libcrypto redland
libcrypto remmina
libgcrypt remmina
libcrypto ricochet
libgcrypt rnetclient
libcrypto rng-tools
libgcrypt rng-tools
libcrypto root
libcrypto R-openssl
libcrypto rpm
libcrypto rsyslog
libgcrypt rsyslog
libcrypto ruby
libcrypto rubygem-eventmachine
libcrypto rubygem-puma
libcrypto rudiments
libcrypto rust
libcrypto rust-gcsf
libcrypto s3fs-fuse
libcrypto sbsigntools
libcrypto seafile
libcrypto sendmail
libcrypto shairport-sync
libcrypto shellinabox
libcrypto siege
libcrypto sipsak
libgcrypt sirikali
libcrypto slrn
libcrypto slurm
libcrypto socat
libcrypto sofia-sip
libcrypto softhsm
libcrypto spasm-ng
libcrypto spice
libcrypto spice-gtk
libcrypto sqlcipher
libcrypto squid
libgcrypt srecord
libcrypto sscg
libcrypto sslsplit
libcrypto ssmtp
libcrypto sssd
libcrypto sstp-client
libcrypto strongswan
libgcrypt strongswan
libcrypto stunnel
libcrypto subscription-manager
libcrypto subsurface
libgcrypt svxlink
libcrypto swift
libcrypto sylpheed
libcrypto synergy
libcrypto sysbench
libcrypto syslog-ng
libgcrypt systemd
libcrypto tarantool
libcrypto tboot
libcrypto tcltls
libcrypto tcpdump
libcrypto tcpflow
libcrypto tcpjunk
libgcrypt tcplay
libcrypto tdlib
libcrypto telegramqml
libcrypto thc-ipv6
libcrypto thrift
libcrypto timescaledb
libcrypto tinc
libcrypto tinyfugue
libcrypto tn5250
libcrypto tnftp
libcrypto tntnet
libcrypto tog-pegasus
libcrypto tomcat-native
libcrypto tor
libcrypto torque
libgcrypt totem-pl-parser
libcrypto tpm2-tools
libcrypto tpm2-tss
libcrypto tpm-tools
libcrypto transmission
libcrypto tripwire
libcrypto trousers
libcrypto trustedqsl
libcrypto tss2
libcrypto uboot-tools
libgcrypt uget
libcrypto unbound
libcrypto uperf
libcrypto up-imapproxy
libgcrypt usbguard
libcrypto uw-imap
libcrypto vboot-utils
libcrypto vdr-epg2vdr
libcrypto vdr-epg-daemon
libcrypto vdr-scraper2vdr
libcrypto vfrnav
libgcrypt vino
libcrypto voms
libcrypto voms-mysql-plugin
libgcrypt vpnc
libcrypto vsftpd
libcrypto warzone2100
libgcrypt webkit2gtk3
libgcrypt weechat
libcrypto wesnoth
libgcrypt wireshark
libcrypto wpa_supplicant
libgcrypt wpewebkit
libcrypto wt
libcrypto x3270
libcrypto xca
libgcrypt xfce4-mailwatch-plugin
libcrypto xl2tpd
libcrypto xmlrpc-c
libcrypto xmlsec1
libgcrypt xmlsec1
libcrypto xml-security-c
libcrypto xmms2
libcrypto xorg-x11-server
libcrypto xrdp
libcrypto xrootd
libcrypto yadifa
libcrypto yapet
libcrypto yara
libgcrypt yaz
libcrypto yubico-piv-tool
libcrypto yubihsm-shell
libcrypto zabbix
libcrypto zbackup
libcrypto zchunk
libcrypto zfs-fuse
libcrypto znc
libgcrypt zulucrypt
</pre>

**Comment by zackw** [comment]
lib(x)crypt is not a replacement for general-purpose cryptography libraries like libcrypto or libgcrypt.   It only does passphrase hashing.  It is a drop-in replacement for the [`crypt*`](http://pubs.opengroup.org/onlinepubs/9699919799/functions/crypt.html) functions that are currently provided by the C library on most Unixes, and _only_ for those functions.

I'm going to take this report as a request to clarify the documentation so that nobody gets the impression we are a general-purpose cryptography library.  Can you explain how you got that impression in the first place?

**Comment by zackw** [comment]
I'm closing this issue because, in the absence of any further information, I don't know what to clarify about the documentation.  If you ever get back to this query please feel free to reopen.
