### ISSUE TITLE
Algorithms in crypt-hashes.h are misordered when using gawk < 4.1.0

### ISSUE THREAD

**Issue by crypto-das** [besser82/libxcrypt#94]
Replacing `for (i in output_order) {` with `for (i = 0; i < next_output; ++i) {` in lib/gen-hashes.awk solved the problem for me.

**Comment by besser82** [comment]
Thanks for your finding!

Can you please paste a diff `diff -Nau` of `crypt-hashes.h`, so we can examine the issue a bit further?

**Comment by besser82** [comment]
It seems that changing the syntax of the loop doesn't generate any harm for more recent versions of gawk.  Let's see what TravisCI come up with.

**Comment by besser82** [comment]
Travis is fine with the patch.  Will merge then.

**Comment by besser82** [comment]
I'll also tag a new release `v4.4.10` for your convenience.

**Comment by crypto-das** [comment]
I'm not sure that understood you correctly (I'm not experienced with diff) but here is diff of the file I got with an old gawk and a file I expect to be generated from hashes.lst: https://gist.github.com/crypto-das/50e6dfbdb180c581caa191027b75f9bf
The main drawback is the default algorithm, which is not yescrypt here.
P.S. Sorry for late answer and thank you for your work!
